### PR TITLE
added methods to authentication

### PR DESCRIPTION
**Pull request by radicaldrew**
added methods for checking if user
has identity and getting the user identity.
this will be used in slim methods
to check if user logged in.

### CODE REVIEW

**Comment by jeremykendall** [comment]
@radicaldrew Thanks! Would you also update the test suite to cover those new methods?

**Comment by radicaldrew** [comment]
Sure. I have some more than things I want to add as well if that's ok.

**Comment by jeremykendall** [comment]
Add whatever you feel will make the lib easier to use. I'd love to see what you come up with.

**Comment by radicaldrew** [comment]
I have published one package so far for slim framework.
I couldn't find a package to work with slim handlebars that was either done
or working correctly for what I needed.
https://github.com/radicaldrew/slim-handlebars
I made it easier to use handlebars templating with slim.

**Comment by mariusbrn** [comment]
+1

**Comment by jeremykendall** [comment]
Thanks so much for the PR, @radicaldrew. I hope you don't mind that I added it, formatted a bit differently and with unit tests, in this commit: a75028e. Wouldn't have happened without your idea. All the credit is yours :-) Thanks again!

**Pull request closed without merging**
